ToDo3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
]

tasks/urls.py
from django.urls import path
from tasks import views
from .views import *

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout"),
    
    path('',views.home, name='home'),
    path('user/', views.userPage, name='user'),
    path('update/<str:pk>/',views.updateTask, name='update'),
    path('delete/<str:pk>/',views.deleteTask, name='delete'),

    path('aboutus/', views.aboutuspage, name='aboutus'),
    path('contactus/', views.contactuspage, name='contactus'),
    path('privacypolicy/', views.privacypolicypage, name='privacypolicy'),
    path('premium/', views.premiumpage, name='premium'),
    path('pricing/', views.pricingpage, name='pricing'),
    path('team/', views.teampage, name='team'),

    path('activate/<uidb64>/<token>',views.ActivateAccountView,name='activate'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.validators import RegexValidator



# Create your models here.

class MyUserManager(BaseUserManager):
    
    def create_user(self, phone, username, password=None, is_active=True, is_staff=False, is_admin=False):
        # import pdb; pdb.set_trace()
        if not phone:
            raise ValueError("User must have a phone number")
        if not username:
            raise ValueError("User must have an username")
        if not password:
            raise ValueError("User must have a password")

        user_obj = self.model(phone=phone)

        user_obj.set_password(password)

        user_obj.username = username
        user_obj.active = is_active
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, phone, username, password=None):
        user = self.create_user(
            phone,
            username,
            password=password,
            is_staff=True
        )

        return user

    def create_superuser(self, phone, username, password=None):
        user = self.create_user(
            phone,
            username,
            password=password,
            is_staff=True,
            is_admin=True
        )

        return user

class MyUser(AbstractBaseUser, PermissionsMixin):
    #user = models.OneToOneField(MyUser, null=True, blank=True, on_delete=models.CASCADE, related_name='myuser')
    username = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)

    password = models.CharField(max_length=16)
    
    confirm_password = models.CharField(max_length=16)

    email = models.EmailField(max_length=200)
    
    #If you want to use regex as validation than use below & pass it as validator in "phone" field:
    #phoneregex = RegexValidator(regex="^[0-9]{10}$")

    phone = models.CharField(max_length=10, unique=True)
    birthdate = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=500)

    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    
    #timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'phone'

    REQUIRED_FIELDS = ['username']   #It will take 'phone' and 'password' as required one, by default 

    objects = MyUserManager()

    def __str__(self):
        return self.username
    
    def get_full_name(self):
        return self.username
    
    def get_short_name(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active


class Task(models.Model):
    my_user = models.ForeignKey(MyUser, null=True, on_delete=models.SET_NULL, related_name='task')
    title = models.CharField(max_length=200, null=False)
    description = models.TextField()
    complete = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def task_description(self):
        return self.description
    
    class Meta:
        ordering = ['-date_created']


class SMTPTable(models.Model):
    name = models.CharField(max_length=120, unique=True)
    backend = models.CharField(max_length=500)
    host = models.CharField(max_length=500)
    port = models.IntegerField()
    tls = models.BooleanField(default=True)
    user = models.EmailField(max_length=200)
    user_password = models.CharField(max_length=20)

    def __str__(self):
        return self.name

tasks/forms.py
import pytz
import re

from datetime import date

from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from tasks.models import Task, MyUser
from django.core.exceptions import ValidationError

utc = pytz.utc
utc_now = date.today()

class TaskForm(forms.ModelForm):
    
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Add new task.....'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Add Description of task.....'}))

    class Meta:
        model = Task
        fields = '__all__'
        exclude = ['my_user']

class UserRegisterationForm(ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = MyUser
        fields = ['username','firstname','lastname','email','password','confirm_password','birthdate','phone','address']

    def clean(self):
        cleaned_data = super(UserRegisterationForm, self).clean()
        password = cleaned_data["password"]
        password2 = cleaned_data["confirm_password"]
        if password != password2:
            raise forms.ValidationError("Password doesn't match")
        return password
    

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if MyUser.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken")
        return username

    
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        phone_validation = re.findall("\d", phone)
        if MyUser.objects.filter(phone=phone).exists():
            raise forms.ValidationError("This phone number is already taken")

        if len(phone)!=10:
            raise forms.ValidationError("The phone number must be of 10 digits")

        if len(phone_validation)!=10:
            raise forms.ValidationError("The phone number must be of numberic only")
        return phone


    def clean_birthdate(self):
        birthdate = self.cleaned_data.get("birthdate")
        if birthdate > utc_now:
            raise forms.ValidationError("Date of Birth cannot be in future")
        return birthdate


    def clean_firstname(self):
        firstname = self.cleaned_data.get("firstname")
        lastname = self.cleaned_data.get("lastname")
        if firstname == lastname:
            raise ValidationError("Fisrtname and Lastname can't be same")

        return firstname

    
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if len(email) > 6:
            if re.match('\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b', email) != None:
                raise ValidationError("Email is not proper")
        return email

tasks/views.py
import pytz
import re

from datetime import date
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group, User
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from django.core import mail
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.db import models
from django.forms.models import model_to_dict
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import TemplateView

from ToDo3.settings import *
from tasks.forms import UserRegisterationForm, TaskForm
from tasks.models import *
from .decorators import unauthenticated_user
from .utils import token_generator

# Create your views here.

@unauthenticated_user
def registerPage(request):
    regform = UserRegisterationForm()

    if request.method == "POST":       
        regform = UserRegisterationForm(request.POST)
        if regform.is_valid(): 
            user_form = regform.save(commit=False)
            
            password = regform.cleaned_data.get('password')
            user_email = regform.cleaned_data.get('email')
            name = regform.cleaned_data.get('firstname')
                
            user_form.password=make_password(password)
            user_form.save()
            user_pk = user_form.pk
            
            user = MyUser.objects.get(pk=user_pk)

            email_settings = SMTPTable.objects.get(name='registration')
            my_backend = email_settings.backend
            my_host = email_settings.host
            my_port = email_settings.port
            my_user = email_settings.user
            myuser_password = email_settings.user_password
            my_tls = email_settings.tls

            current_site = get_current_site(request)
            email_subject = 'Activation of your ToDoApp Account'
            message = render_to_string('tasks/email_template.html',
            {
                'user':user, 'domain':current_site.domain, 'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':token_generator.make_token(user), 'name':name,
            }
            )

            connection = mail.get_connection(backend=my_backend,host=my_host, 
                            port=my_port, 
                            username=my_user, 
                            password=myuser_password, 
                            use_tls=my_tls)
            print("Conn ------>",connection)
            connection.open()
            email_registartion = mail.EmailMessage(email_subject,message,my_user,[user_email],connection=connection)
            email_registartion.send()
            connection.close()

            return HttpResponse("Please first confirm your email address to complete the registeration")
    else:
        regform = UserRegisterationForm()

    context = {'myform':regform}
    return render(request,'tasks/register.html',context)


@unauthenticated_user
def loginPage(request):
    if request.method == "POST":
        
        phone = request.POST.get('phone')
        password = request.POST.get('password')

        user_var = MyUser.objects.get(phone=phone)
        user_mail = user_var.email
        user = authenticate(request, phone=phone, password=password)

        email_settings = SMTPTable.objects.get(name='login')
        my_backend = email_settings.backend
        my_host = email_settings.host
        my_port = email_settings.port
        my_user = email_settings.user
        myuser_password = email_settings.user_password
        my_tls = email_settings.tls
        
        if user is not None:
            login(request, user)
            email_subject = 'Welcome to ToDo App'
            message = render_to_string('tasks/email_template_2.html')

            connection = mail.get_connection(backend=my_backend,host=my_host, 
                            port=my_port, 
                            username=my_user, 
                            password=myuser_password, 
                            use_tls=my_tls)
            connection.open()
            email_login = mail.EmailMessage(email_subject,message,my_user,[user_mail],connection=connection)
            email_login.send()
            connection.close()
            return redirect('user')
        else:
            messages.info(request,'Phone Number or Password is incorrect')

    context = {}
    return render(request,'tasks/login.html',context)

@login_required(login_url='login')
def logoutPage(request):
    logout(request)
    return redirect('login')


def home(request):
    return render(request, 'tasks/home.html')


@login_required(login_url='login')
def updateTask(request, pk):
    task = Task.objects.get(id=pk)
    form  = TaskForm(instance=task)

    user_name = request.user.firstname
    user_mail = request.user.email

    email_settings = SMTPTable.objects.get(name="create_and_update")
    my_backend = email_settings.backend
    my_host = email_settings.host
    my_port = email_settings.port
    my_user = email_settings.user
    myuser_password = email_settings.user_password
    my_tls = email_settings.tls

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid:
            form.save()

            email_subject = 'Update in your ToDo Task'
            message = render_to_string('tasks/email_template_update.html',{'name':user_name})

            connection = mail.get_connection(backend=my_backend,host=my_host, 
                            port=my_port, 
                            username=my_user, 
                            password=myuser_password, 
                            use_tls=my_tls)
            connection.open()
            email_login = mail.EmailMessage(email_subject,message,my_user,[user_mail],connection=connection)
            email_login.send()
            connection.close()
            return redirect('user')
    
    context = {'form':form}
    return render(request,'tasks/user.html',context)


@login_required(login_url='login')
def deleteTask(request, pk):
    item = Task.objects.get(id = pk)

    if request.method == 'POST':
        item.delete()
        return redirect('user')

    context = {'item':item}
    return render(request, 'tasks/delete.html',context)


@login_required(login_url='login')
def userPage(request):
    tasks = Task.objects.filter(my_user=request.user)

    form = TaskForm()

    user_mail = request.user.email
    user_name = request.user.firstname

    email_settings = SMTPTable.objects.get(name="create_and_update")
    my_backend = email_settings.backend
    my_host = email_settings.host
    my_port = email_settings.port
    my_user = email_settings.user
    myuser_password = email_settings.user_password
    my_tls = email_settings.tls

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid:
            Task_form = form.save(commit=False)
            Task_form.my_user = request.user
            Task_form.save()

            email_subject = 'New Creation of task in your ToDo Task'
            message = render_to_string('tasks/email_template_create.html',{'name':user_name})

            connection = mail.get_connection(backend=my_backend,host=my_host, 
                            port=my_port, 
                            username=my_user, 
                            password=myuser_password, 
                            use_tls=my_tls)
            connection.open()
            email_login = mail.EmailMessage(email_subject,message,my_user,[user_mail],connection=connection)
            email_login.send()
            connection.close()
        return redirect('user')

    context ={'TASKS':tasks, 'form':form}

    return render(request,'tasks/user.html',context)

def aboutuspage(request):
    return render(request,'tasks/Aboutus.html')


def contactuspage(request):
    return render(request,'tasks/Contactus.html')


def teampage(request):
    return render(request,'tasks/Team.html')


def privacypolicypage(request):
    return render(request,'tasks/PrivacyPolicy.html')


def pricingpage(request):
    return render(request,'tasks/Pricing.html')


def premiumpage(request):
    return render(request,'tasks/Premium.html')


def ActivateAccountView(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = MyUser.objects.get(pk=uid)
    except Exception as identifier:
        user = None
    if user is not None and token_generator.check_token(user, token):
        user.save()
        messages.add_message(request,messages.INFO,'ACCOUNT IS ACTIVATED SUCCESSFULLY')
        return redirect('login')
    else:
        return render(request,'tasks/activate_failed.html',status=401)

tasks/templates/tasks/Aboutus.html
<h3>This is About Us Page</h3>

tasks/templates/tasks/Contactus.html
<h3>This is Contact Us Page</h3>

tasks/templates/tasks/PrivacyPolicy.html
<h3>This is Privacy Policy Page</h3>

tasks/templates/tasks/email_template.html
{% autoescape off %}


Hey {{name}}

Welcome to ToDoApp, 

Complete the this step to register your account, by clicking the link given below :

http://{{domain}}{% url 'activate' uidb64=uid token=token %}

Best regards from,
ToDoApp Team.

{% endautoescape %}

tasks/templates/tasks/email_template_2.html
{% autoescape off %}


Hey

Welcome to ToDoApp, 

Hope you like your service....... 
And incase if there is any trouble contact us..... 


Best regards from,
ToDoApp Team.

{% endautoescape %}

tasks/templates/tasks/email_template_create.html
{% autoescape off %}


Hey {{name}}

Welcome to ToDoApp, 

**** Alert ****

Created a new task ...... 
Hope you find your comfort in using this app and for any help contact us at .....  

Best regards from,
ToDoApp Team.

{% endautoescape %}

tasks/templates/tasks/email_template_update.html
{% autoescape off %}


Hey {{name}}

Welcome to ToDoApp, 

**** Alert ****

Updated a task ...... 
Hope you find your comfort in using this app and for any help contact us at .....  

Best regards from,
ToDoApp Team.

{% endautoescape %}

tasks/templates/tasks/home.html
{% extends 'tasks/main.html' %}

{% block content %}

<h3>HOME PAGE OF ToDo App</h3>

{% endblock %}

tasks/templates/tasks/list.html
<h3>To Do App</h3>

<form method="POST" action="">
    {% csrf_token %}

    {{form.title}}
    <input type="submit" name="Create Task">
</form>

{% for task in tasks %}
    <div>
        <p>{{task}}</p>
    </div>
{% endfor %}

tasks/templates/tasks/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: rgba(88, 111, 185, 0.8) !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">

                        {% csrf_token %}
                        
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-phone"></i></span>
							</div>
							<input type="text" name="phone" placeholder="Phone Number..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

                </div>
                
                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>

					<br>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

tasks/templates/tasks/main.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>ToDo App</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    </head>

    <body>       
        {% include 'tasks/navbar.html'%}
        <div class="container-fluid">
            <hr>
            {% block content %} 
        
        
            {% endblock %}
        </div>
        <hr>


        <footer class="page-footer font-small special-color-dark pt-4" style="bottom: 0; padding-top: 20px;">


          <div class="container-fluid text-center text-md-left">

            <!-- Grid row -->
            <div class="row">
        
              <!-- Grid column -->
              <div class="col-md-6 mt-md-0 mt-3">
        
                <!-- Content -->
                <h5 class="text-uppercase">Why Choose Us?</h5>
                <p>We help people to organize their tasks in day-to-day working life.</p>
        
              </div>
        
              <hr class="clearfix w-100 d-md-none pb-3">
        
              <!-- Grid column -->
              
              <div class="col-md-3 mb-md-0 mb-3">

                <h5 class="text-uppercase">Features</h5>
        
                <ul class="list-unstyled">
                  <li>
                    <span><a href="{% url 'pricing' %}">Pricing</a></span>
                  </li>
                  <li>
                    <span><a href="{% url 'premium' %}">Premium</a></span>
                  </li>
                </ul>
        
              </div>


              <div class="col-md-3 mb-md-0 mb-3">
        
                <h5 class="text-uppercase">COMPANY</h5>
        
                <ul class="list-unstyled">
                  <li>
                    <span><a href="{% url 'aboutus' %}">About Us</a></span>
                  </li>
                  <li>
                    <span><a href="{% url 'team' %}">Our Team</a></span>
                  </li>
                  <li>
                    <span><a href="{% url 'privacypolicy' %}">Privacy Policy</a></span>
                  </li>
                  <li>
                    <span><a href="{% url 'contactus' %}">Contact Us</a></span>
                  </li>
                </ul>
        
              </div>

            </div>

          </div>


          <br>
          <br>
          <br>
            <!-- Social buttons -->
            <ul class="list-unstyled list-inline text-center">
              <li class="list-inline-item">
                <a class="btn-floating btn-fb mx-1" href="https://www.facebook.com">
                  <i class="fa fa-facebook-square white-text mr-md-3 mr-3 fa-2x "> </i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-tw mx-1" href="https://www.twitter.com">
                  <i class="fa fa-twitter-square white-text mr-md-3 mr-3 fa-2x"> </i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-gplus mx-1" href="https://www.googleplus.com">
                  <i class="fa fa-google-plus-square white-text mr-md-3 mr-3 fa-2x"> </i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-li mx-1" href="https://www.linkedin.com">
                  <i class="fa fa-linkedin-square white-text mr-md-3 mr-3 fa-2x"> </i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-in mx-1" href="https://www.instagram.com">
                  <i class="fa fa-instagram white-text mr-md-3 mr-3 fa-2x"> </i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-pin mx-1" href="https://www.pinterest.com">
                  <i class="fa fa-pinterest white-text mr-md-3 mr-3 fa-2x"> </i>
                </a>
              </li>
            </ul>
        
          </div>
          
        
          <div class="footer-copyright text-center py-3">© 2020 Copyright:
            <a href="https://ToDoApp.com/"> ToDoApp.com</a>
          </div>
        
        </footer>
        

    </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</html>

tasks/templates/tasks/password_reset_form.html
{% extends 'tasks/main.html' %}

{% block content %}


<h3></h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="POST">
    
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit" name="Update Password">

</form>

{% endblock %}

tasks/templates/tasks/user.html
{% extends 'tasks/main.html' %}

{% block content %}

<style>
    #id_description{
        height: 200px;
        width: 300px;
    }

    #id_title{
        height: 50px;
        width: 300px;
    }
</style>

<div class="center-column">

    <h3>YOUR LIST OF TASKS</h3>

    <form method="POST" action="" id="createTasks" data-url="{% url 'user' %}">
        {% csrf_token %}
        <p style="padding-left: 25px;">Title: {{form.title}} <span style="padding-left: 15px;">Complete:{{form.complete}}</span></p>   
        <p>Description: {{form.description}}</p>
        <button class="btn btn-col btn-primary" type="submit">Create Task</button>


        {% for Task in TASKS %}
            <div class="item-row">
                <a class="btn btn-sm btn-info" href="{% url 'update' Task.id %}">Update</a>
                <a class="btn btn-sm btn-danger" href="{% url 'delete' Task.id %}">Delete</a>

                {% if Task.complete == True %}
                <br>
                <strike>{{Task.title}}</strike>
                <br>
                <br>
                <strike>{{Task.description}}</strike>
                {% else %}
                <br>
                <span>{{Task.title}}</span>
                <br>
                <br>
                <span>{{Task.description}}</span>
                {% endif %}
            </div>
        {% endfor %}

    </form>

    
        <div class="col-12 mt-5" id="showTasks">
            {% for Task in MYTASKS %}
            <div class="item-row" id="tasksrow" data-id="{{ Task.id }}">
                <span>{{Task.title}}</span>
                <br>
                <br>
                <span>{{Task.description}}</span>
            </div>
        {% endfor %}
        </div>


</div>

{% endblock %}